"""
Excel to PDF Converter - Bank Statement Style
Creates professional bank statement PDFs from Excel data
Works reliably on Render.com without LibreOffice
Uses reportlab to create professional PDFs matching Bank of India format
"""

import os
import tempfile
import pandas as pd
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.units import inch, mm
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime


def convert_excel_to_pdf_table(excel_path, output_path, account_info=None, logo_path=None):
    """
    Convert Excel to PDF with professional table formatting and headers/footers.
    """
    print(f"\n{'='*60}")
    print(f"EXCEL TO PDF - Professional Table Conversion")
    print(f"Input: {os.path.basename(excel_path)}")
    print(f"{'='*60}\n")

    try:
        df = pd.read_excel(excel_path)
        print(f"✓ Read {len(df)} rows x {len(df.columns)} columns")

        page_size = A4
        if len(df.columns) > 8:
            from reportlab.lib.pagesizes import landscape
            page_size = landscape(A4)
            print("✓ Using LANDSCAPE orientation")

        doc = BaseDocTemplate(output_path, pagesize=page_size)
        
        # Define frames and page template
        frame = Frame(doc.leftMargin, doc.bottomMargin, doc.width, doc.height - 20*mm, id='normal')
        template = PageTemplate(id='main', frames=[frame], onPage=lambda canvas, doc: _header_footer(canvas, doc, logo_path))
        doc.addPageTemplates([template])

        elements = _build_story(df, account_info)
        
        doc.build(elements)

        file_size = os.path.getsize(output_path) / 1024
        print(f"✓ PDF created: {os.path.basename(output_path)} ({file_size:.2f} KB)")
        print(f"{'='*60}\n")
        return output_path

    except Exception as e:
        print(f"ERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        return None


def _header_footer(canvas, doc, logo_path):
    """Draws the header and footer for each page."""
    canvas.saveState()
    width, height = doc.pagesize

    # Header
    if logo_path and os.path.exists(logo_path):
        canvas.drawImage(logo_path, doc.leftMargin, height - 15*mm, width=30*mm, preserveAspectRatio=True)
    canvas.setFont('Helvetica-Bold', 12)
    canvas.drawCentredString(width / 2.0, height - 12*mm, "Statement of Transactions")

    # Footer
    canvas.setFont('Helvetica', 9)
    canvas.drawString(doc.leftMargin, 10*mm, f"Page {doc.page}")
    canvas.drawCentredString(width / 2.0, 10*mm, "Generated by PDFTools")
    canvas.drawRightString(width - doc.rightMargin, 10*mm, datetime.now().strftime("%Y-%m-%d %H:%M"))
    canvas.restoreState()

def _build_story(df, account_info):
    """Builds the story with all the elements for the PDF."""
    elements = []
    styles = getSampleStyleSheet()

    # Title
    title = Paragraph("Transaction Details", styles['h1'])
    elements.append(title)
    elements.append(Spacer(1, 6*mm))

    # Account Info
    if account_info:
        info_text = f"<b>Account Holder:</b> {account_info.get('account_holder_name', 'N/A')}<br/>"
        info_text += f"<b>Account Number:</b> {account_info.get('account_number', 'N/A')}"
        elements.append(Paragraph(info_text, styles['Normal']))
        elements.append(Spacer(1, 6*mm))

    # Table
    table = _create_table(df)
    elements.append(table)

    return elements

def _create_table(df):
    """Creates and styles the transaction table."""
    table_data = [df.columns.tolist()] + df.values.tolist()
    
    # Dynamic column widths
    page_width = A4[0] - 40*mm
    num_cols = len(df.columns)
    col_widths = [page_width / num_cols] * num_cols

    table = Table(table_data, colWidths=col_widths, repeatRows=1)
    
    style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4F81BD')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ])
    table.setStyle(style)

    return table

def convert_csv_to_pdf_table(csv_path, output_path, account_info=None, logo_path=None):
    """
    Convert CSV to PDF with proper table formatting.
    This function is kept for compatibility but now acts as a wrapper.
    """
    try:
        df = pd.read_csv(csv_path, encoding='utf-8', on_bad_lines='skip')
        with tempfile.NamedTemporaryFile(suffix='.xlsx', delete=False) as tmp:
            df.to_excel(tmp.name, index=False)
            return convert_excel_to_pdf_table(tmp.name, output_path, account_info, logo_path)
    except Exception as e:
        print(f"ERROR converting CSV: {e}")
        return None


# Main conversion function
def convert_to_pdf_table(input_path, output_path, account_info=None, logo_path=None):
    """
    Main conversion function - handles both Excel and CSV
    
    account_info: Optional dict with account details for bank statement format
                  Keys: customer_id, account_holder_name, account_number, address,
                        transaction_date_from, transaction_date_to, amount_from, 
                        amount_to, cheque_from, cheque_to, transaction_type
    logo_path: Optional path to bank logo image
    """
    if input_path.lower().endswith('.csv'):
        return convert_csv_to_pdf_table(input_path, output_path, account_info=account_info, logo_path=logo_path)
    else:
        return convert_excel_to_pdf_table(input_path, output_path, account_info=account_info, logo_path=logo_path)


# Test function
if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 2:
        print("Usage: python excel_to_pdf_table.py <excel_or_csv_file> [logo_file]")
        sys.exit(1)
    
    input_file = sys.argv[1]
    if not os.path.exists(input_file):
        print(f"ERROR: File not found: {input_file}")
        sys.exit(1)
    
    # Optional logo
    logo_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    # Output path
    base_name = os.path.splitext(os.path.basename(input_file))[0]
    output_dir = os.path.dirname(input_file) or '.'
    output_file = os.path.join(output_dir, f"{base_name}.pdf")
    
    result = convert_to_pdf_table(input_file, output_file, logo_path=logo_file)
    
    if result:
        print(f"\n✓ SUCCESS: {result}")
    else:
        print(f"\n✗ FAILED")
        sys.exit(1)
